const newsSources = [
    {
        num: 0,
        name: 'Democracy Now',
        url: 'https://www.democracynow.org/democracynow.rss',
        currentData: null, 
        logo: 'https://assets.democracynow.org/assets/logo2-8566131fa2436fa4d6d18e6997cd58cda60253174a99078c681b6643aa38a558.png',
    },
    {
        index: 1,
        name: 'New York Times',
        url: 'https://rss.nytimes.com/services/xml/rss/nyt/US.xml',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/NewYorkTimes.svg/278px-NewYorkTimes.svg.png?20190313030219',
    },
    {
        index: 2,
        name: 'Daily Mail',
        url: 'https://www.dailymail.co.uk/news/worldnews/index.rss',
        currentData: null,
        logo: 'https://logos-download.com/wp-content/uploads/2016/06/The_Daily_Mail_logo_wordmark.png',
    },
    {
        index: 3,
        name: 'The Hill',
        url: 'https://thehill.com/homenews/feed/',
        currentData: null,
        logo: 'https://logos-download.com/wp-content/uploads/2019/01/The_Hill_Logo-700x700.png',
    },
    {
        index: 4,
        name: 'Daily Beast',
        url: 'https://feeds.thedailybeast.com/rss/articles',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/af/The_Daily_Beast_%28logo%29.svg/512px-The_Daily_Beast_%28logo%29.svg.png?20230306033236',
    },
    {
        index: 5,
        name: 'Axios',
        url: 'https://api.axios.com/feed/',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Axios_logo_%282020%29.svg/225px-Axios_logo_%282020%29.svg.png?20200902175018',
    },
    {
        index: 6,
        name: 'New Yorker',
        url: 'https://www.newyorker.com/feed/news',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/The_New_Yorker_Logo.svg/501px-The_New_Yorker_Logo.svg.png?20171007215353',
    },
    {
        index: 7,
        name: 'BBC',
        url: 'https://rss.app/feeds/N4kBzbL3HYwQBNe3.xml',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/BBC_Logo_2021.svg/1920px-BBC_Logo_2021.svg.png',
    },
    {
        index: 8,
        name: 'The Dispatch',
        url: 'https://thedispatch.com/feed/',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/The_Dispatch_logo.svg/2560px-The_Dispatch_logo.svg.png',
    },
    {
        index: 9,
        name: 'The Blaze',
        url: 'https://www.theblaze.com/feeds/feed.rss',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/TheBlaze_new_logo.svg/749px-TheBlaze_new_logo.svg.png?20170214223500',
    },
    {
        index: 10,
        name: 'Breitbart',
        url: 'https://feeds.feedburner.com/breitbart',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Breitbart_News.svg/1280px-Breitbart_News.svg.png',
    },
    {
        index: 11,
        name: 'The Federalist',
        url: 'https://thefederalist.com/feed/',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/The_Federalist_logo.png',
    },
    {
        index: 12,
        name: 'One America News',
        url: 'https://www.oann.com/feed',
        currentData: null,
        logo: 'https://cloudfront-us-east-1.images.arcpublishing.com/dmn/CLILOWH3NFHPDOU66J6HVEQ47I.png',
    },
    {
        index: 13,
        name: 'Washington Free Beacon',
        url: 'https://freebeacon.com/feed/',
        currentData: null,
        logo: 'https://www.allsides.com/sites/default/files/source-logos/freebeacon.png',
    },
    {
        index: 14,
        name: 'National Review',
        url: 'https://www.nationalreview.com/feed/',
        currentData: null,
        logo: 'https://www.nationalreview.com/wp-content/themes/national-review/static/images/social.jpg',
    },
    {
        index: 15,
        name: 'Reason',
        url: 'https://reason.com/feed/',
        currentData: null,
        logo: 'https://d2eehagpk5cl65.cloudfront.net/wp-content/themes/reason-dot-com-theme/dist/images/logo_2ea65906.svg',
    },
    {
        index: 16,
        name: 'Sky News - World',
        url: 'https://feeds.skynews.com/feeds/rss/world.xml',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Sky_News_logo.svg/2560px-Sky_News_logo.svg.png',
    },
    {
        index: 17,
        name: 'Salon',
        url: 'https://www.salon.com/feed',
        currentData: null,
        logo: 'https://www.salon.com/design/images/salon-logo.svg'
    },
    {
        index: 18,
        name: 'Mediaite',
        url: 'https://www.mediaite.com/feed/',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Mediaite_Logo_2019.svg/1200px-Mediaite_Logo_2019.svg.png?20190820110819',
    },
    {
        index: 19,
        name: 'Der Spiegel - International',
        url: 'http://www.spiegel.de/schlagzeilen/rss/0,5291,676,00.xml',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Logo-der_spiegel.svg/1200px-Logo-der_spiegel.svg.png?20180720182838',
    },
    {
        index: 20,
        name: 'Marketwatch',
        url: 'http://feeds.marketwatch.com/marketwatch/topstories/',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/MarketWatch_Logo.svg/1920px-MarketWatch_Logo.svg.png',
    },
    {
        index: 21,
        name: 'Jerusalem Post',
        url: 'https://rss.jpost.com/rss/rssfeedsfrontpage.aspx',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Jerusalem_Post_Logo.svg/495px-Jerusalem_Post_Logo.svg.png?20130726094339',
    },
    {
        index: 22,
        name: 'Real Clear Politics',
        url: 'https://www.realclearpolitics.com/index.xml',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/RCPlogoNew.png',
    },
    {
        index: 23,
        name: 'Boston Globe - US News',
        url: 'https://www.boston.com/tag/national-news/feed/',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/The_Boston_Globe.svg/2560px-The_Boston_Globe.svg.png',
    },
    {
        index: 24,
        name: 'New York Post',
        url: 'https://nypost.com/feed/',
        currentData: null,
        logo: 'https://upload.wikimedia.org/wikipedia/commons/1/13/New_York_Post_logo.png?20071126081910',
    },
    {
        index: 25,
        name: 'The Sun US',
        url: 'https://www.the-sun.com/feed/',
        logo: 'https://www.the-sun.com/wp-content/uploads/sites/6/2020/01/cropped-UsSunFavicon.png?strip=all&#038;w=32'
    },
    {
        index: 26,
        name: 'Russia Today',
        url: 'https://www.rt.com/rss/',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Russia-today-logo.svg'
    },
    {
        index: 27,
        name: 'New Tang Dynasty',
        url: 'https://api.ntd.com/feed',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/NTD_Logo_with_symbol.svg/210px-NTD_Logo_with_symbol.svg.png?20211113150733',
    },
    {
        index: 28,
        name: 'Wall Street Journal - World News',
        url: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/WSJ_Logo.svg/2560px-WSJ_Logo.svg.png',
    },
    {
        index: 29,
        name: 'CNBC - US News',
        url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15837362',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/CNBC_logo.svg',
    },
    {
        index: 30,
        name: 'FiveThirtyEight',
        url: 'https://fivethirtyeight.com/all/feed',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/FiveThirtyEight_Logo.svg/1280px-FiveThirtyEight_Logo.svg.png',
    },
    {
        index: 31,
        name: 'Vox',
        url: 'https://www.vox.com/rss/index.xml',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vox_logo.svg/1200px-Vox_logo.svg.png',
    },
    {
        index: 32,
        name: 'Washington Post',
        url: 'https://feeds.washingtonpost.com/rss/world?itid=lk_inline_manual_36',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/The_Logo_of_The_Washington_Post_Newspaper.svg/1200px-The_Logo_of_The_Washington_Post_Newspaper.svg.png',
    },
    {
        index: 33,
        name: 'Slate',
        url: 'https://slate.com/feeds/all.rss',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Slate_new_logo.svg/2560px-Slate_new_logo.svg.png',
    },
    {
        index: 34,
        name: 'The Intercept',
        url: 'https://theintercept.com/feed/?lang=en',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/The_Intercept_logo.svg/768px-The_Intercept_logo.svg.png?20180418214604',
    }
];

export default newsSources;